version: '3.1'

services:

  owncloud:
    image: owncloud
    restart: always
    ports:
      - 8898:80

  mysql:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456