version: '3.1'

services:

  owncloud:
    image: owncloud
    restart: always
    ports:
      - 8898:80
    volumes:
      - ./data/data:/var/www/html/data
      - ./data/apps:/var/www/html/apps
      - ./data/config:/var/www/html/config

  mysql:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
    volumes:
      - ./data/mysql:/var/lib/mysql